services:
  nextjs-app:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    container_name: nextjs-app
    env_file:
      - .env
    depends_on:
      - database
    ports: 
      - '3000:3000'
    networks:
      - con-db

  database:
    image: 'postgres:16.3-alpine'
    container_name: database
    env_file:
      - .env
    ports:
      - '5432'
    networks:
      - con-db
    restart: always

networks:
  con-db:
    driver: bridge